language: generic

sudo: required

dist: xenial

os:
  - linux

jobs:
  include:
    - compiler: gcc
      name: 'Native builds'
      before_install:
        - ./scripts/travis.sh "$TRAVIS_OS_NAME" initialize

      script:
        - pyenv global 3.7.1
        - ./scripts/travis.sh "$TRAVIS_OS_NAME" build
    - services:
        - docker
      name: 'Docker build'
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
      script:
        - clang-8 -emit-llvm -c ./tests/tools/decomp/issue_4.c -o ./tests/tools/decomp/issue_4.bc
        - docker build -t rellic-decomp --build-arg LLVM_VERSION=8.0 .
        - |
          docker run --rm -t \
            -v "$(pwd)":/test -w /test \
            -u "$(id -u)":"$(id -g)" \
            rellic-decomp:latest --input ./tests/tools/decomp/issue_4.bc --output /dev/stdout
