language: generic

sudo: required

dist: xenial

os:
  - linux

compiler:
  - gcc

before_install:
  - ./scripts/travis.sh "$TRAVIS_OS_NAME" initialize

script:
  - pyenv global 3.7.1
  - ./scripts/travis.sh "$TRAVIS_OS_NAME" build
