language: generic

python: 3.7

sudo: required

dist: xenial

os:
  - linux

compiler:
  - gcc

before_install:
  - ./scripts/travis.sh "$TRAVIS_OS_NAME" initialize

script:
  - ./scripts/travis.sh "$TRAVIS_OS_NAME" build
